// This file is auto-generated by vite-plugin-generate-svg-icons
// Do not edit this file manually

export { default as IconArrowRight } from '~icons/base/arrow-right'
export { default as IconLoading } from '~icons/base/loading'
export { default as IconReact } from '~icons/base/react'
