// This file is auto-generated by vite-plugin-generate-svg-icons
// Do not edit this file manually
/**
 * <svg xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 24 24"><path fill="#8d8d8d" d="M11.5 4A8.5 8.5 0 0 0 3 12.5H2A9.5 9.5 0 0 1 11.5 3z"/></svg>
 */
export { default as IconArrowRight } from '~icons/base/arrow-right'
export { default as IconLoading } from '~icons/base/loading'
export { default as IconReact } from '~icons/base/react'
